async function loadReportOptions() {
    const opts = await apiGet('../php/inventory_action.php?action=options');
    document.getElementById('category').innerHTML = opts.categories.map(o => `<option value="${o.id}">${o.name}</option>`).join('');
    document.getElementById('businessType').innerHTML += opts.business_types.map(o => `<option value="${o.id}">${o.name}</option>`).join('');
    if (window.jQuery && jQuery.fn.select2) {
        jQuery('#category').select2({
            placeholder: 'All Categories',
            allowClear: true,
            closeOnSelect: false,
            width: '100%'
        }).on('change', runReport);
    }
}

async function runReport() {
    const params = new URLSearchParams({
        action: 'run',
        type: reportType.value,
        from: dateFrom.value,
        to: dateTo.value,
        categories: Array.from(category.selectedOptions).map(option => option.value).filter(Boolean).join(','),
        business_type: businessType.value,
        status: status.value,
    });
    const data = await apiGet(`../php/reports_action.php?${params}`);
    reportTitle.textContent = data.title;
    reportMeta.textContent = `Date range: ${data.range} | Generated by: ${data.generated_by} | Date generated: ${data.generated_at}`;
    reportHead.innerHTML = `<tr>${data.columns.map(c => `<th>${c}</th>`).join('')}</tr>`;
    reportBody.innerHTML = data.rows.map(row => `<tr>${data.keys.map(k => `<td>${row[k] ?? ''}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${data.columns.length}" class="text-center">No records found.</td></tr>`;
}

document.getElementById('runReport').onclick = runReport;
loadReportOptions().then(runReport);
